version:  '3'
services:
  odse:
      build: ./
      ports:
        - 8888:8888
      command: "start-notebook.sh"
      environment:
        - JUPYTER_TOKEN=odse2022
      volumes:
        - ../:/home/jovyan/odse-workshop-2022
